version: 2.1
jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-14-tools-deps-1.10.1.502-buster-node
        environment:
          JDBC_URL: jdbc:pgsql://localhost:5432/postgres?user=postgres&password=password"
      - image: circleci/postgres:12.3
        environment:
          POSTGRES_PASSWORD: password

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "deps.edn" }}

      - run: clojure -R:dev:clj-test:cljs-test -e "(prn :deps)"

      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
          key: v1-dependencies-{{ checksum "deps.edn" }}

      - run: clojure -A:dev:clj-test
      - run: clojure -A:dev:cljs-test
